create table product (id bigint generated by default as identity, active boolean, date_created timestamp, description varchar(255), image_url varchar(255), last_updated timestamp, name varchar(255), sku varchar(255), unit_price decimal(19,2), units_in_stock integer, category_id bigint not null, primary key (id));
create table product_category (id bigint generated by default as identity, category_name varchar(255), primary key (id));
alter table product add constraint FK5cypb0k23bovo3rn1a5jqs6j4 foreign key (category_id) references product_category;
create table product (id bigint generated by default as identity, active boolean, date_created timestamp, description varchar(255), image_url varchar(255), last_updated timestamp, name varchar(255), sku varchar(255), unit_price decimal(19,2), units_in_stock integer, category_id bigint not null, primary key (id));
create table product_category (id bigint generated by default as identity, category_name varchar(255), primary key (id));
alter table product add constraint FK5cypb0k23bovo3rn1a5jqs6j4 foreign key (category_id) references product_category;
create table product (id bigint generated by default as identity, active boolean, date_created timestamp, description varchar(255), image_url varchar(255), last_updated timestamp, name varchar(255), sku varchar(255), unit_price decimal(19,2), units_in_stock integer, category_id bigint not null, primary key (id));
create table product_category (id bigint generated by default as identity, category_name varchar(255), primary key (id));
alter table product add constraint FK5cypb0k23bovo3rn1a5jqs6j4 foreign key (category_id) references product_category;
